### ISSUE TITLE
reimplement index and show apis in student quiz controller

### ISSUE THREAD

**Issue by prathyu99** [prathyu99/reimplementation-back-end#2]

**Comment by srilakshmikotha** [comment]
For the index action - 880658fdb903eef263cc29bc2ff77be9dba1d1cd
- Modified the index action to wrap the returned quiz list within a `render_success` method for standardized API response formatting.
- Changed the instance variable `@quizzes` to a local variable `quizzes`, as instance variables are not required for the local scope of the action.
- This refactoring does not alter the core functionality but standardizes the API responses across the platform.

For the show action - 65a054c6929a747772e58d34a2bdb3cb93d83bbd
- Updated the show action to use the `render_success` method, aligning the response structure with the rest of the API endpoints.
- This update does not change the logic for retrieving the student quiz; rather, it envelops the student_quiz object in a standardized response format.
